export default [
    "Aardvark",
    "Aardwolf",
    "Abyssinian",
    "Addax",
    "Adelie Penguin",
    "Affenpinscher",
    "Afghan Hound",
    "African Bullfrog",
    "African Bush Elephant",
    "African Civet",
    "African Clawed Frog",
    "African Forest Elephant",
    "African Grey Parrot",
    "African Palm Civet",
    "African Penguin",
    "African Tree Toad",
    "African Wild Dog",
    "Aidi",
    "Ainu",
    "Ainu Dog",
    "Airedale Terrier",
    "Akbash",
    "Akita",
    "Akita Shepherd",
    "Alaskan Husky",
    "Alaskan Klee Kai",
    "Alaskan Malamute",
    "Alaskan Shepherd",
    "Albacore Tuna",
    "Albatross",
    "Aldabra Giant Tortoise",
    "Alligator",
    "Alligator Gar",
    "Alpaca",
    "Alpine Dachsbracke",
    "Alpine Goat",
    "Alusky",
    "Amazon Parrot",
    "Ambrosia Beetle",
    "American Alsatian",
    "American Bulldog",
    "American Cocker Spaniel",
    "American Cockroach",
    "American Coonhound",
    "American Eskimo Dog",
    "American Foxhound",
    "American Hairless Terrier",
    "American Leopard Hound",
    "American Pit Bull Terrier",
    "American Pygmy Goat",
    "American Robin",
    "American Staffordshire Terrier",
    "American Toad",
    "American Water Spaniel",
    "Amur Leopard",
    "Anatolian Shepherd Dog",
    "Anchovies",
    "Angelfish",
    "Anglerfish",
    "Ant",
    "Antarctic scale worm",
    "Anteater",
    "Antelope",
    "Ape",
    "Appenzeller Dog",
    "Apple Head Chihuahua",
    "Arapaima",
    "Arctic Fox",
    "Arctic Hare",
    "Arctic Wolf",
    "Arizona Bark Scorpion",
    "Armadillo",
    "Asian Elephant",
    "Asian Giant Hornet",
    "Asian Palm Civet",
    "Asiatic Black Bear",
    "Aurochs",
    "Aussiedoodle",
    "Aussiedor",
    "Australian Cattle Dog",
    "Australian Gecko",
    "Australian Kelpie Dog",
    "Australian Labradoodle",
    "Australian Mist",
    "Australian Shepherd",
    "Australian Terrier",
    "Avocet",
    "Axolotl",
    "Aye Aye",
    "Babirusa",
    "Baboon",
    "Bactrian Camel",
    "Badger",
    "Bald Eagle",
    "Baleen Whale",
    "Balinese",
    "Banana Ball Python",
    "Banana Spider",
    "Banded Palm Civet",
    "Banded Water Snake",
    "Bandicoot",
    "Barb",
    "Barbet",
    "Barn Owl",
    "Barnacle",
    "Barracuda",
    "Barramundi Fish",
    "Basenji Dog",
    "Basking Shark",
    "Basset Hound",
    "Bassetoodle",
    "Bat",
    "Bavarian Mountain Hound",
    "Bea-Tzu",
    "Beagle",
    "Beagle Shepherd",
    "Beaglier",
    "Beago",
    "Bear",
    "Bearded Collie",
    "Bearded Dragon",
    "Beaski",
    "Beauceron",
    "Beaver",
    "Bed Bugs",
    "Bedlington Terrier",
    "Bee",
    "Beefalo",
    "Beetle",
    "Bengal Tiger",
    "Bergamasco",
    "Berger Picard",
    "Bernedoodle",
    "Bernese Mountain Dog",
    "Bichir",
    "Bichon Frise",
    "Bichpoo",
    "Biewer Terrier",
    "Bighorn Sheep",
    "Bilby",
    "Binturong",
    "Bird",
    "Birds Of Paradise",
    "Birman",
    "Biscuit Beetle",
    "Bison",
    "Black Bear",
    "Black Rhinoceros",
    "Black Russian Terrier",
    "Black Wasp",
    "Black Widow Spider",
    "Black-Footed Ferret",
    "Blood Python",
    "Bloodhound",
    "Blue Iguana",
    "Blue Lacy Dog",
    "Blue Picardy Spaniel",
    "Blue Shark",
    "Blue Whale",
    "Blue grosbeak",
    "Blue whale",
    "Blue-Ringed Octopus",
    "Bluefin Tuna",
    "Bluetick Coonhound",
    "Boar",
    "Bobcat",
    "Bolognese Dog",
    "Bombay",
    "Bongo",
    "Bonito Fish",
    "Bonnethead Shark",
    "Bonobo",
    "Booby",
    "Boomslang",
    "Border Collie",
    "Border Terrier",
    "Borkie",
    "Bornean Orang-utan",
    "Borneo Elephant",
    "Boston Terrier",
    "Bottle Nosed Dolphin",
    "Bottlenose Dolphin",
    "Bouvier Des Flandres",
    "Bowfin",
    "Box Turtle",
    "Boxador",
    "Boxer Dog",
    "Boxsky",
    "Boxweiler",
    "Boykin Spaniel",
    "Brazilian Terrier",
    "British Timber",
    "Brittany",
    "Brookesia Micra",
    "Brown Bear",
    "Brown Hyena",
    "Brown Water Snake",
    "Brug",
    "Brussels Griffon",
    "Budgerigar",
    "Buffalo",
    "Bull Mastiff",
    "Bull Shark",
    "Bull Terrier",
    "Bulldog",
    "Bullfrog",
    "Bullmastiff",
    "Bumble Bee",
    "Burmese",
    "Burmese Python",
    "Burrowing Frog",
    "Bush Baby",
    "Butterfly",
    "Butterfly Fish",
    "Cactus Mouse",
    "Caecilian",
    "Caiman",
    "Caiman Lizard",
    "Cairn Terrier",
    "Camel",
    "Camel Cricket",
    "Camel Spider",
    "Canaan Dog",
    "Canadian Horse",
    "Canary",
    "Cane Corso",
    "Capybara",
    "Caracal",
    "Caribou",
    "Carolina Dog",
    "Carolina Parakeet",
    "Carp",
    "Carpenter Ant",
    "Cassowary",
    "Cat",
    "Catahoula Leopard",
    "Caterpillar",
    "Catfish",
    "Cattle",
    "Cava Tzu",
    "Cavador",
    "Cavalier King Charles Spaniel",
    "Cavapoo",
    "Centipede",
    "Cesky Fousek",
    "Chameleon",
    "Chamois",
    "Chartreux",
    "Cheagle",
    "Cheetah",
    "Chesapeake Bay Retriever",
    "Chickadee",
    "Chicken",
    "Chihuahua",
    "Chimaera",
    "Chimpanzee",
    "Chinchilla",
    "Chinese Crested Dog",
    "Chinese Geese",
    "Chinese Paddlefish",
    "Chinese Shar-Pei",
    "Chinese unicorn",
    "Chinook",
    "Chinstrap Penguin",
    "Chipmunk",
    "Chiweenie",
    "Chorkie",
    "Chow Chow",
    "Chow Shepherd",
    "Cicada",
    "Cichlid",
    "Clam",
    "Clouded Leopard",
    "Clown Fish",
    "Clownfish",
    "Clumber Spaniel",
    "Coati",
    "Cobra",
    "Cockalier",
    "Cockapoo",
    "Cockatiel",
    "Cockatoo",
    "Cockroach",
    "Cod",
    "Codfish",
    "Coelacanth",
    "Collared Peccary",
    "Collie",
    "Colossal Squid",
    "Common Buzzard",
    "Common Frog",
    "Common Loon",
    "Common Raven",
    "Common Toad",
    "Condor",
    "Cookiecutter Shark",
    "Cooper's Hawk",
    "Coral",
    "Corgidor",
    "Corgipoo",
    "Corkie",
    "Corman Shepherd",
    "Cottonmouth",
    "Cottontop Tamarin",
    "Cougar",
    "Cow",
    "Coyote",
    "Crab",
    "Crab Spider",
    "Crab-Eating Macaque",
    "Crane",
    "Crappie Fish",
    "Crested Gecko",
    "Crested Penguin",
    "Cricket",
    "Crocodile",
    "Cross Fox",
    "Cross River Gorilla",
    "Crow",
    "Cuckoo",
    "Curly Coated Retriever",
    "Cuscus",
    "Cuttlefish",
    "Dachsador",
    "Dachshund",
    "Dalmador",
    "Dalmatian",
    "Darwin's Frog",
    "Darwin's fox",
    "Deer",
    "Deer Head Chihuahua",
    "Desert Locust",
    "Desert Rain Frog",
    "Desert Tortoise",
    "Deutsche Bracke",
    "Devon Rex",
    "Dhole",
    "Dik-Dik",
    "Dingo",
    "Discus",
    "Doberman Pinscher",
    "Dodo",
    "Dog",
    "Dogo Argentino",
    "Dogue De Bordeaux",
    "Dolphin",
    "Donkey",
    "Dorkie",
    "Dormouse",
    "Douc",
    "Dove",
    "Doxiepoo",
    "Doxle",
    "Dragonfish",
    "Dragonfly",
    "Drever",
    "Duck",
    "Dugong",
    "Dung Beetle",
    "Dunker",
    "Dusky Dolphin",
    "Dwarf Crocodile",
    "Eagle",
    "Earthworm",
    "Earwig",
    "Eastern Chipmunk",
    "Eastern Fence Lizard",
    "Eastern Glass Lizard",
    "Eastern Gorilla",
    "Eastern Lowland Gorilla",
    "Eastern Phoebe",
    "Echidna",
    "Edible Frog",
    "Eel",
    "Egyptian Mau",
    "Electric Eel",
    "Elephant",
    "Elephant Seal",
    "Elephant Shrew",
    "Elk",
    "Emperor Penguin",
    "Emperor Tamarin",
    "Emu",
    "English Cocker Spaniel",
    "English Foxhound",
    "English Pointer",
    "English Setter",
    "English Shepherd",
    "English Springer Spaniel",
    "Entlebucher Mountain Dog",
    "Epagneul Pont Audemer",
    "Ermine",
    "Eskimo Dog",
    "Estrela Mountain Dog",
    "Eurasian Beaver",
    "Eurasian Lynx",
    "European Polecat",
    "European Wildcat",
    "Falcon",
    "Fallow deer",
    "False Killer Whale",
    "Fangtooth",
    "Feist",
    "Fennec Fox",
    "Ferret",
    "Ferruginous Hawk",
    "Fiddler Crab",
    "Field Spaniel",
    "Fila Brasileiro",
    "Fin Whale",
    "Finch",
    "Finnish Spitz",
    "Fire salamander",
    "Fire-Bellied Toad",
    "Firefly",
    "Fish",
    "Fisher Cat",
    "Fishing Cat",
    "Flamingo",
    "Flat Coat Retriever",
    "Flea",
    "Florida Gar",
    "Florida Panther",
    "Flounder",
    "Flowerhorn Fish",
    "Fly",
    "Flying Fish",
    "Flying Squirrel",
    "Fossa",
    "Fox",
    "Fox Squirrel",
    "Fox Terrier",
    "French Bulldog",
    "Frenchton",
    "Frigatebird",
    "Frilled Lizard",
    "Frog",
    "Frogfish",
    "Fruit Fly",
    "Fur Seal",
    "Gaboon Viper",
    "Galapagos Penguin",
    "Galapagos Tortoise",
    "Gar",
    "Garden Eel",
    "Garter Snake",
    "Gazelle",
    "Gecko",
    "Genet",
    "Gentoo Penguin",
    "Geoffroys Tamarin",
    "Gerbil",
    "German Pinscher",
    "German Shepherd",
    "German Sheppit",
    "German Spitz",
    "Gharial",
    "Ghost Crab",
    "Giant African Land Snail",
    "Giant Armadillo",
    "Giant Clam",
    "Giant Panda Bear",
    "Giant Schnauzer",
    "Giant panda",
    "Gibbon",
    "Gila Monster",
    "Giraffe",
    "Glass Lizard",
    "Glechon",
    "Glow Worm",
    "Gnat",
    "Goat",
    "Goberian",
    "Goblin Shark",
    "Goldador",
    "Golden Dox",
    "Golden Lion Tamarin",
    "Golden Newfie",
    "Golden Oriole",
    "Golden Pyrenees",
    "Golden Retriever",
    "Golden Shepherd",
    "Goldendoodle",
    "Goldfish",
    "Goliath Frog",
    "Goose",
    "Gopher",
    "Gorilla",
    "Gouldian Finch",
    "Grasshopper",
    "Gray Fox",
    "Gray Tree Frog",
    "Great Blue Heron",
    "Great Dane",
    "Great White Shark",
    "Greater Swiss Mountain Dog",
    "Green Anole",
    "Green Bee-Eater",
    "Green Frog",
    "Green Tree Frog",
    "Greenland Dog",
    "Greenland Shark",
    "Grey Mouse Lemur",
    "Grey Reef Shark",
    "Grey Seal",
    "Greyhound",
    "Grizzly Bear",
    "Groenendael",
    "Grouse",
    "Guinea Fowl",
    "Guinea Pig",
    "Gull",
    "Guppy",
    "Haddock",
    "Hagfish",
    "Hammerhead Shark",
    "Hamster",
    "Harbor Seal",
    "Hare",
    "Harp Seal",
    "Harpy Eagle",
    "Harrier",
    "Harris Hawk",
    "Havanese",
    "Havapoo",
    "Havashire",
    "Hawaiian Crow",
    "Hawk",
    "Hedgehog",
    "Hellbender",
    "Hercules Beetle",
    "Hermit Crab",
    "Heron",
    "Herring",
    "Highland Cattle",
    "Himalayan",
    "Hippopotamus",
    "Hoary Bat",
    "Hokkaido",
    "Honey Badger",
    "Honey Bee",
    "Honeybee",
    "Hooded Seal",
    "Hoopoe",
    "Horn Shark",
    "Hornbill",
    "Horned Frog",
    "Horned Viper",
    "Horse",
    "Horsefly",
    "Horseshoe Crab",
    "House Finch",
    "House wren",
    "Housefly",
    "Howler Monkey",
    "Human",
    "Humboldt Penguin",
    "Humboldt Squid",
    "Hummingbird",
    "Humpback Whale",
    "Huntaway",
    "Huntsman Spider",
    "Huskador",
    "Husky",
    "Husky Jack",
    "Huskydoodle",
    "Hyena",
    "Ibex",
    "Ibis",
    "Ibizan Hound",
    "Iguana",
    "Impala",
    "Imperial Moth",
    "Indian Cobra",
    "Indian Elephant",
    "Indian Palm Squirrel",
    "Indian Rhinoceros",
    "Indian Star Tortoise",
    "Indochinese Tiger",
    "Indri",
    "Insect",
    "Insects",
    "Irish Setter",
    "Irish Terrier",
    "Irish WolfHound",
    "Italian Greyhound",
    "Jacana",
    "Jack Russel",
    "Jackabee",
    "Jackal",
    "Jackdaw",
    "Jackrabbit",
    "Jaguar",
    "Jaguarundi Cat",
    "Japanese Beetle",
    "Japanese Chin",
    "Japanese Macaque",
    "Japanese Spitz",
    "Japanese Terrier",
    "Javan Rhinoceros",
    "Javanese",
    "Jellyfish",
    "Jerboa",
    "Jumping Spider",
    "Kai Ken",
    "Kakapo",
    "Kangal",
    "Kangaroo",
    "Kangaroo Rat",
    "Keel Billed Toucan",
    "Keeshond",
    "Key Deer",
    "Kiko Goat",
    "Killer Whale",
    "King Cobra",
    "King Crab",
    "King Penguin",
    "King Shepherd",
    "Kingfisher",
    "Kishu",
    "Kit Fox",
    "Kiwi",
    "Koala",
    "Koi Fish",
    "Komodo Dragon",
    "Kookaburra",
    "Krill",
    "Kudu",
    "LaMancha Goat",
    "Labahoula",
    "Labradoodle",
    "Labrador Retriever",
    "Labraheeler",
    "Ladybird",
    "Ladybug",
    "Lamb",
    "Lamprey",
    "Lapponian Herder",
    "Leaf-Tailed Gecko",
    "Leech",
    "Lemming",
    "Lemur",
    "Leonberger",
    "Leopard",
    "Leopard Cat",
    "Leopard Frog",
    "Leopard Seal",
    "Leopard Tortoise",
    "Lhasa Apso",
    "Lhasapoo",
    "Liger",
    "Lion",
    "Lionfish",
    "Little Brown Bat",
    "Little Penguin",
    "Lizard",
    "Llama",
    "Lobster",
    "Locust",
    "Long-Eared Owl",
    "Long-Haired Rottweiler",
    "Longnose Gar",
    "Lorikeet",
    "Louse",
    "Lungfish",
    "Lynx",
    "Lyrebird",
    "Macaroni Penguin",
    "Macaw",
    "Mackenzie Wolf",
    "Magellanic Penguin",
    "Maggot",
    "Magpie",
    "Maine Coon",
    "Malayan Civet",
    "Malayan Tiger",
    "Mallard",
    "Maltese",
    "Maltipoo",
    "Manatee",
    "Mandrill",
    "Maned Wolf",
    "Manta Ray",
    "Mantella Frog",
    "Marble Fox",
    "Marine Toad",
    "Markhor",
    "Marmot",
    "Marsh Frog",
    "Masked Palm Civet",
    "Massasauga",
    "Mastiff",
    "Mayfly",
    "Mealybug",
    "Meerkat",
    "Mekong Giant Catfish",
    "Mexican Alligator Lizard",
    "Miki",
    "Milk Snake",
    "Milkfish",
    "Millipede",
    "Miniature Bull Terrier",
    "Miniature Husky",
    "Miniature Pinscher",
    "Mink",
    "Minke Whale",
    "Mole",
    "Mole Cricket",
    "Molly",
    "Mongoose",
    "Mongrel",
    "Monitor Lizard",
    "Monkey",
    "Monte Iberia Eleuth",
    "Moorhen",
    "Moose",
    "Moray Eel",
    "Mosquito",
    "Moth",
    "Mountain Cur",
    "Mountain Feist",
    "Mountain Gorilla",
    "Mountain Lion",
    "Mouse",
    "Mudi",
    "Mule",
    "Muntjac",
    "Muskrat",
    "Narwhal",
    "Neanderthal",
    "Neapolitan Mastiff",
    "Nebelung",
    "Newfoundland",
    "Newfypoo",
    "Newt",
    "Nigerian Goat",
    "Nightingale",
    "Nile Crocodile",
    "Norfolk Terrier",
    "Northern Alligator Lizard",
    "Northern Cardinal",
    "Northern Inuit Dog",
    "Norwegian Buhund",
    "Norwegian Forest",
    "Norwich Terrier",
    "Nubian Goat",
    "Numbat",
    "Nurse Shark",
    "Nyala",
    "Ocelot",
    "Octopus",
    "Okapi",
    "Old English Sheepdog",
    "Olive Baboon",
    "Olm",
    "Opossum",
    "Orang-utan",
    "Orangutan",
    "Oscar Fish",
    "Ostrich",
    "Otter",
    "Owl",
    "Ox",
    "Oyster",
    "Paddlefish",
    "Pademelon",
    "Painted Turtle",
    "Panda",
    "Pangolin",
    "Panther",
    "Papillon",
    "Parakeet",
    "Parrot",
    "Patas Monkey",
    "Peacock",
    "Peacock Butterfly",
    "Peacock Spider",
    "Pekingese",
    "Pelican",
    "Penguin",
    "Pere Davids Deer",
    "Peregrine Falcon",
    "Persian",
    "Pheasant",
    "Pied Tamarin",
    "Pig",
    "Pigeon",
    "Pika",
    "Pike",
    "Pike Fish",
    "Pine Marten",
    "Pine Snake",
    "Pink Fairy Armadillo",
    "Piranha",
    "Pit Bull",
    "Pitsky",
    "Platypus",
    "Pocket Pitbull",
    "Pointer",
    "Poison Dart Frog",
    "Polar Bear",
    "Pomapoo",
    "Pomchi",
    "Pomeagle",
    "Pomeranian",
    "Pomsky",
    "Pond Skater",
    "Poochon",
    "Poodle",
    "Pool Frog",
    "Porcupine",
    "Porpoise",
    "Possum",
    "Potoroo",
    "Prairie Dog",
    "Prawn",
    "Prawns",
    "Praying Mantis",
    "Proboscis Monkey",
    "Pronghorn",
    "Pudelpointer",
    "Puff Adder",
    "Puffer Fish",
    "Puffin",
    "Pug",
    "Pugapoo",
    "Puggle",
    "Pugshire",
    "Puma",
    "Pumi",
    "Purple Emperor",
    "Puss Moth",
    "Pygmy Hippopotamus",
    "Pygmy Marmoset",
    "Pygora Goat",
    "Pyredoodle",
    "Qat",
    "Qilin ",
    "Qiviut",
    "Quagga",
    "Quahog",
    "Quail",
    "Quarter Horse",
    "Queen Snake",
    "Queen Triggerfish",
    "Queensland Heeler",
    "Quetzal",
    "Quirky Quokka",
    "Quokka",
    "Quoll",
    "Rabbit",
    "Raccoon",
    "Raccoon Dog",
    "Radiated Tortoise",
    "Ragamuffin",
    "Ragdoll",
    "Raggle",
    "Rat",
    "Rattlesnake",
    "Raven",
    "Red Finch",
    "Red Fox",
    "Red Knee Tarantula",
    "Red Panda",
    "Red Squirrel",
    "Red Wolf",
    "Red-handed Tamarin",
    "Reef Shark",
    "Reindeer",
    "Rhinoceros",
    "River Dolphin",
    "River Otter",
    "River Turtle",
    "Robin",
    "Rock Crab",
    "Rock Hyrax",
    "Rockfish",
    "Rockhopper Penguin",
    "Rodents",
    "Roe Deer",
    "Rooster",
    "Roseate Spoonbill",
    "Rottsky",
    "Rottweiler",
    "Royal Penguin",
    "Russell Terrier",
    "Russian Blue",
    "Russian Tortoise",
    "Saanen Goat",
    "Saarloos Wolfdog",
    "Sable",
    "Sabre-Toothed Tiger",
    "Saiga",
    "Saint Berdoodle",
    "Saint Bernard",
    "Salamander",
    "Salmon",
    "Saluki",
    "Samoyed",
    "Sand Crab",
    "Sand Lizard",
    "Sand Viper",
    "Sandpiper",
    "Saola",
    "Sardines",
    "Savanna Goat",
    "Sawfish",
    "Scarlet Macaw",
    "Schipperke",
    "Schnoodle",
    "Scorpion",
    "Scorpion Fish",
    "Scottish Terrier",
    "Scrotum Frog",
    "Sea Dragon",
    "Sea Eagle",
    "Sea Lion",
    "Sea Otter",
    "Sea Slug",
    "Sea Squirt",
    "Sea Turtle",
    "Sea Urchin",
    "Sea horse",
    "Seahorse",
    "Seal",
    "Sealion",
    "Sei Whale",
    "Serval",
    "Shark",
    "Sheep",
    "Sheepadoodle",
    "Shepadoodle",
    "Shepkita",
    "Shiba Inu",
    "Shih Poo",
    "Shih Tzu",
    "Shollie",
    "Shrew",
    "Shrimp",
    "Siamese",
    "Siamese Fighting Fish",
    "Siberian",
    "Siberian Husky",
    "Siberian Ibex",
    "Siberian Tiger",
    "Siberpoo",
    "Silky Terrier",
    "Silver Dollar",
    "Sixgill shark",
    "Skate Fish",
    "Skink Lizard",
    "Skunk",
    "Sleeper Shark",
    "Sloth",
    "Slow Worm",
    "Slug",
    "Snail",
    "Snake",
    "Snapping Turtle",
    "Snorkie",
    "Snowshoe",
    "Snowshoe Hare",
    "Snowy Owl",
    "Somali",
    "Song Sparrow",
    "Song Thrush",
    "South China Tiger",
    "Spadefoot Toad",
    "Sparrow",
    "Spectacled Bear",
    "Sperm Whale",
    "Spider",
    "Spider Monkey",
    "Spinner Shark",
    "Spinone Italiano",
    "Spiny Dogfish",
    "Spiny Hill Turtle",
    "Spitting Cobra",
    "Sponge",
    "Squash Beetle",
    "Squid",
    "Squirrel",
    "Squirrel Monkey",
    "Sri Lankan Elephant",
    "Staffordshire Bull Terrier",
    "Stag Beetle",
    "Standard Schnauzer",
    "Star-nosed mole",
    "Starfish",
    "Stellers Sea Cow",
    "Stick Insect",
    "Stiletto Snake",
    "Stingray",
    "Stoat",
    "Stone Crab",
    "Stork",
    "Striped Rocket Frog",
    "Sturgeon",
    "Sucker Fish",
    "Sugar Gliders",
    "Sumatran Elephant",
    "Sumatran Orang-utan",
    "Sumatran Rhinoceros",
    "Sumatran Tiger",
    "Sun Bear",
    "Swan",
    "Swedish Vallhund",
    "Syrian Hamster",
    "Takin",
    "Tamaskan",
    "Tang",
    "Tapanuli Orang-utan",
    "Tapir",
    "Tarantula Hawk",
    "Tarpon",
    "Tarsier",
    "Tasmanian Devil",
    "Tasmanian Tiger",
    "Tawny Owl",
    "Termite",
    "Terrier",
    "Tetra",
    "Thorny Devil",
    "Thrush",
    "Tibetan Fox",
    "Tibetan Mastiff",
    "Tick",
    "Tiffany",
    "Tiger",
    "Tiger Beetle",
    "Tiger Salamander",
    "Tiger Shark",
    "Toad",
    "Toadfish",
    "Tortoise",
    "Toucan",
    "Toy Poodle",
    "Tree Frog",
    "Tree Kangaroo",
    "Tree swallow",
    "Tropicbird",
    "Trout",
    "Tsetse Fly",
    "Tuatara",
    "Tuna",
    "Turkey",
    "Turkish Angora",
    "Turtle",
    "Turtles",
    "Uakari",
    "Uguisu",
    "Uinta ground squirrel",
    "Umbrellabird",
    "Unicorn fish",
    "Urial",
    "Ursine colugo",
    "Urutu",
    "Utonagan",
    "Uzara bush",
    "Vampire Bat",
    "Vampire Squid",
    "Vaquita",
    "Vervet Monkey",
    "Vicuña",
    "Vinegaroon",
    "Vizsla",
    "Vulture",
    "Walking Catfish",
    "Wallaby",
    "Walleye Fish",
    "Walrus",
    "Warthog",
    "Wasp",
    "Water Buffalo",
    "Water Dragon",
    "Water Vole",
    "Weasel",
    "Welsh Corgi",
    "Welsh Terrier",
    "West Highland Terrier",
    "Western Gorilla",
    "Western Lowland Gorilla",
    "Westiepoo",
    "Whale",
    "Whale Shark",
    "Wheaten Terrier",
    "Whippet",
    "Whiptail Lizard",
    "White Butterfly",
    "White Faced Capuchin",
    "White Rhinoceros",
    "White Tiger",
    "White-Tailed Eagle",
    "White-tail deer",
    "Whooping Crane",
    "Wild Boar",
    "Wildebeest",
    "Wire Fox Terrier",
    "Wolf",
    "Wolf Eel",
    "Wolf Spider",
    "Wolffish",
    "Wolverine",
    "Wombat",
    "Wood Frog",
    "Wood Turtle",
    "Woodlouse",
    "Woodlouse Spider",
    "Woodpecker",
    "Woolly Mammoth",
    "Woolly Monkey",
    "Worm",
    "Wrasse",
    "Writing Spider",
    "X-Ray Tetra",
    "Xerus",
    "Xoloitzcuintli",
    "Yak",
    "Yellow-Eyed Penguin",
    "Yellowfin Tuna",
    "Yeti Crab",
    "Yorkie Bichon",
    "Yorkshire Terrier",
    "Zebra",
    "Zebra Finch",
    "Zebra Pleco",
    "Zebra Shark",
    "Zebu",
    "Zonkey",
    "Zorse",
];
